/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-12-07 10:49:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class formatorai_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Usuario/Desktop/Proyecto/proyecto-dawi-master/Proyecto/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DAWI-Semana01-Plantilla(8)/WEB-INF/lib/standard.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098729090000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1607337859656L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"esS\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css\"/>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<title>Formato Rai</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.modal-header, h4, .close {\r\n");
      out.write("\t\tbackground-color: #286090;\r\n");
      out.write("\t\tcolor: white !important;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.help-block{\r\n");
      out.write("\t color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.form-group.has-error .form-control-label {\r\n");
      out.write("\t  color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.form-group.has-error .form-control {\r\n");
      out.write("\t  border: 1px solid red;\r\n");
      out.write("\t  box-shadow: 0 0 0 0.2rem rgba(250, 16, 0, 0.18);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.dataTables_length{\r\n");
      out.write("\t display: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dataTables_filter{\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dataTables_info{\r\n");
      out.write("\t display: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dataTables_paginate{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("</style> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fremove_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" data-backdrop=\"static\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <!-- Modal Header -->\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\">Sistema</h4>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal body -->\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        \tSeguro de eliminar formato? \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal footer -->\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <form action=\"deleteFormato\" method=\"post\" name=\"myForm\">\t\r\n");
      out.write("\t\t  \t  <input type=\"hidden\" id=\"idNumero\" name=\"codigo\">\r\n");
      out.write("\t             <button type=\"submit\" class=\"btn btn-primary\">SI</button>\r\n");
      out.write("\t             <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">NO</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h3 align=\"center\">Lista de Formato RAI</h3>\r\n");
      out.write("\t\t<button type=\"button\" data-toggle='modal'  data-target=\"#idModalRegistra\" id=\"idNuevo\"\r\n");
      out.write("\t\t\t\tclass='btn btn-primary' >Nuevo Formato RAI</button><br>&nbsp;<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div id=\"divEmpleado\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t<table id=\"idTable\" class=\"table table-striped table-bordered\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Codigo</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Descripcion</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Fuentes</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Contenido</th>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Area de Plan de Trabajo</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Apellido del Usuario</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- INICIO DIV NUEVO -->\r\n");
      out.write("<div class=\"modal fade bd-example-modal-lg\" id=\"idModalRegistra\" data-backdrop=\"static\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"padding: 5px 20px\">\r\n");
      out.write("\t\t\t\t\tRegistro de Formato RAI<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          \t\t\t\t\r\n");
      out.write("       \t\t\t\t   </button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 20px 20px;\">\r\n");
      out.write("\t\t\t\t\t<form id=\"idRegistra\" accept-charset=\"UTF-8\" action=\"saveFormato\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-horizontal\" method=\"post\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"validator\" role=\"form\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"idCodigo\" name=\"formato.codigo\" value=\"0\">\t\t\t\t\t\r\n");
      out.write("\t\t                                \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                                   \t<label for=\"staticEmail\">Descripcion</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"idNombre\" name=\"formato.descip\" placeholder=\"Ingrese  Nombres\"/>\r\n");
      out.write("\t\t\t                                </div>    \r\n");
      out.write("\t\t                                    <div class=\"form-row\">\r\n");
      out.write("\t\t\t                                    <div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t                                        <label for=\"staticEmail\">Fuentes</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"idFuentes\" name=\"formato.fuentes\" placeholder=\"Ingrese Apellidos\"/>\r\n");
      out.write("\t\t\t                                    </div>\r\n");
      out.write("\t\t\t                                    <div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t                                        <label for=\"staticEmail\">Contenido</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"idContenido\" name=\"formato.contenido\" placeholder=\"Ingrese Edad\"/>\r\n");
      out.write("\t\t\t                                    </div>\r\n");
      out.write("\t\t\t                                \t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"idCodUsr\" value=\"1\" name=\"formato.codUsr\" type=\"hidden\" placeholder=\"Ingrese Edad\"/>\r\n");
      out.write("\t\t\t                                    </div>\r\n");
      out.write("\t\t\t                                </div>   \r\n");
      out.write("\t\t                                    <div class=\"form-group\">\r\n");
      out.write("\t\t                                        <label for=\"staticEmail\">Tipo</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"idFormato\" name=\"formato.codPlanT\" class='form-control'>\r\n");
      out.write("\t\t\t\t\t\t\t                                 <option value=\" \" >[SELECCIONE]</option>\r\n");
      out.write("\t\t\t\t\t\t\t                         </select>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("                        \t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\" id=\"btnCerrar\">Cerrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"submit\" class=\"btn btn-primary\">Guardar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t            </form>      \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("<!-- FIN DIV NUEVO -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrapValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tllenarTipos();\r\n");
      out.write("\tllenarMercaderias();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//variable global\r\n");
      out.write("var codPlan=0;\r\n");
      out.write("\r\n");
      out.write("function llenarMercaderias(){\r\n");
      out.write("\t$.getJSON(\"listAllPlan\",{},function (response){\r\n");
      out.write("\t\t\t\t$.each(response.listaPlan,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#idFormato\").append(\"<option value='\"+item.codigo+\"'>\"+item.area+\"</option>\");\r\n");
      out.write("\t\t\t\t})\t\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("function llenarTipos(){\r\n");
      out.write("\t$.getJSON(\"listAllFormato\",{},function (response){\r\n");
      out.write("\t\t\t\t$.each(response.listaFormato,function(index,item){\r\n");
      out.write("\t\t\t\t\tvar editar=\"<button type='button' class='btn btn-secondary' data-toggle='modal'  id='idEditar' data-target='#idModalRegistra'>Editar</button>\";\r\n");
      out.write("\t\t\t\t\tvar eliminar=\"<button type='button' class='btn btn-danger' data-toggle='modal' \"+\r\n");
      out.write("\t\t\t\t\t \"data-target='#myModal' id='idEliminar'>Eliminar</button>\";\r\n");
      out.write("\t\t\t\t\t$(\"#idTable\").append(\"<tr><td>\"+item.codigo+\"</td><td>\"+item.descip+\"</td><td>\"+item.fuentes+ \r\n");
      out.write("\t\t\t\t\t\t\t \"</td><td>\"+item.contenido+\"</td><td>\"+item.area+\"</td><td>\"+item.apellidos+\"</td><td>\"+eliminar+\"</td><td>\"+editar+\"</td></tr>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t})\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#idTable\").DataTable();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#success-alert\").fadeTo(3000,1, function(){\t\r\n");
      out.write("    $(\"#success-alert\").slideUp(500);\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '#idEliminar', function(){\r\n");
      out.write("    var id = $(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("    $(\"#idNumero\").val(id);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '#idEditar', function(){\r\n");
      out.write("    var id = $(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("    $.getJSON(\"findFormato\",{codigo:id},function (response){\r\n");
      out.write("\t\t$(\"#idCodigo\").val(id); \r\n");
      out.write("\t\t$(\"#idNombre\").val(response.formato.descip);\r\n");
      out.write("\t\t$(\"#idFuentes\").val(response.formato.fuentes);\r\n");
      out.write("\t\t$(\"#idContenido\").val(response.formato.contenido);\r\n");
      out.write("\t\t$(\"#idCodUsr\").val(response.formato.codUsr);\r\n");
      out.write("\t\t$(\"#idFormato\").val(response.formato.codPlanT);\r\n");
      out.write("\t\t//alacenar el valor de tipo de medicamento en la variable global codTipo\r\n");
      out.write("\t\tcodPlan=response.formato.codigoPlan;\r\n");
      out.write("\t\t//invocar al evento change del select idLaboratorio\r\n");
      out.write("\t\t$(\"#idFormato\").trigger(\"change\");\r\n");
      out.write("    })  \r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("$(document).on('click', '#btnCerrar', function(){\r\n");
      out.write("\t$('#idRegistra').data('bootstrapValidator').resetForm(true);\r\n");
      out.write("    $('#idRegistra').trigger(\"reset\");\r\n");
      out.write("\t$(\"#idCodigo\").val(0); \r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">    \r\n");
      out.write("    $(document).ready(function(){     \r\n");
      out.write("        $('#idRegistra').bootstrapValidator({      \r\n");
      out.write("        \t fields:{\r\n");
      out.write("        \t\t \r\n");
      out.write("        \t\t Nombre: {\r\n");
      out.write("     \t    \t\tselector:'#idNombre',   \r\n");
      out.write("                    validators: {    \r\n");
      out.write("                        notEmpty: {    \r\n");
      out.write("                            message: 'Ingrese nombre'    \r\n");
      out.write("                        },      \r\n");
      out.write("                        regexp: {    \r\n");
      out.write("                            regexp: /^[a-zA-Z\\s]+$/,    \r\n");
      out.write("                            message: 'campo nombres solo letras'    \r\n");
      out.write("                        },\r\n");
      out.write("                        notEmpty: {    \r\n");
      out.write("                            message: 'El minimo es 3 caracteres'    \r\n");
      out.write("                        },\r\n");
      out.write("                    \t stringLength: {\r\n");
      out.write("                    \t\t min: 3,\r\n");
      out.write("                             max: 30,\r\n");
      out.write("                             message: 'El maximo es 45 caracteres'\r\n");
      out.write("                         }, \r\n");
      out.write("                    }    \r\n");
      out.write("                },   \r\n");
      out.write("                \r\n");
      out.write("                Stock: {\r\n");
      out.write("     \t    \t\tselector:'#idStock',   \r\n");
      out.write("                    validators: {  \r\n");
      out.write("                    \tinteger: {\r\n");
      out.write("                        message: 'Solo acepta valores Enteros'\r\n");
      out.write("                    },\r\n");
      out.write("                    }    \r\n");
      out.write("                },     \r\n");
      out.write("                \r\n");
      out.write("                Precio: {\r\n");
      out.write("     \t    \t\tselector:'#idPrecio',      \r\n");
      out.write("                    validators: {    \r\n");
      out.write("                        notEmpty: {    \r\n");
      out.write("                            message: 'Ingrese precio'    \r\n");
      out.write("                        },\r\n");
      out.write("                        regexp: {    \r\n");
      out.write("                            regexp: /^[0-9]{1,10}[.][0-9][0-9]{1,2}$/,    \r\n");
      out.write("                            message: 'Campo número de precio invalido Ejem: 200.00'    \r\n");
      out.write("                        },   \r\n");
      out.write("                    }    \r\n");
      out.write("                },      \t\t\t\t\r\n");
      out.write("                Distrito: {\r\n");
      out.write("     \t    \t\tselector:'#idTipo',   \r\n");
      out.write("                    validators: {    \r\n");
      out.write("                        notEmpty: {    \r\n");
      out.write("                            message: 'Seleccione Distrito'    \r\n");
      out.write("                        },\t\t\t\t\t\r\n");
      out.write("                    }    \r\n");
      out.write("                } \r\n");
      out.write("        \t }\r\n");
      out.write("        });   \r\n");
      out.write("\t\t\t\r\n");
      out.write("    });    \r\n");
      out.write("</script>   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /formatorai.jsp(51,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\" id=\"success-alert\">\r\n");
          out.write("  <strong>Sistema:</strong> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("  <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\r\n");
          out.write("    <span aria-hidden=\"true\">&times;</span>\r\n");
          out.write("  </button>\r\n");
          out.write("</div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent(null);
      // /formatorai.jsp(59,0) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("MENSAJE");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
