/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-12-07 00:22:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class informemultiple_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Usuario/Desktop/Proyecto/proyecto-dawi-master/Proyecto/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DAWI-Semana01-Plantilla(8)/WEB-INF/lib/standard.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098729090000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1607282411000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html lang=\"esS\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css\"/>\n");
      out.write(" \n");
      out.write("\n");
      out.write("<title>Medicamento</title>\n");
      out.write("<style>\n");
      out.write("\t.modal-header, h4, .close {\n");
      out.write("\t\tbackground-color: #286090;\n");
      out.write("\t\tcolor: white !important;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tfont-size: 20px;\n");
      out.write("\t}\n");
      out.write("\t.help-block{\n");
      out.write("\t color: red;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.form-group.has-error .form-control-label {\n");
      out.write("\t  color: red;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.form-group.has-error .form-control {\n");
      out.write("\t  border: 1px solid red;\n");
      out.write("\t  box-shadow: 0 0 0 0.2rem rgba(250, 16, 0, 0.18);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t.dataTables_length{\n");
      out.write("\t display: none;\n");
      out.write("\t}\n");
      out.write("\t.dataTables_filter{\n");
      out.write("\t\ttext-align: right;\n");
      out.write("\t}\n");
      out.write("\t.dataTables_info{\n");
      out.write("\t display: none;\n");
      out.write("\t}\n");
      out.write("\t.dataTables_paginate{\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t}\n");
      out.write("</style> \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fremove_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<!-- The Modal -->\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" data-backdrop=\"static\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <!-- Modal Header -->\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <h4 class=\"modal-title\">Sistema</h4>\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Modal body -->\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("        \tSeguro de eliminar medicamento? \n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Modal footer -->\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <form action=\"deleteMedicamento\" method=\"post\" name=\"myForm\">\t\n");
      out.write("\t\t  \t  <input type=\"hidden\" id=\"idNumero\" name=\"codigo\">\n");
      out.write("\t             <button type=\"submit\" class=\"btn btn-primary\">SI</button>\n");
      out.write("\t             <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">NO</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- The Modal Mensaje-->\n");
      out.write("  <div class=\"modal fade\" id=\"myModalMensaje\" data-backdrop=\"static\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <!-- Modal Header -->\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <h4 class=\"modal-title\">Sistema</h4>\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Modal body -->\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("        \t<p id=\"idMen\"></p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Modal footer -->\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("           <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Cerrar</button>\n");
      out.write("\t    </div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("<!-- The Modal FOTO-->\n");
      out.write("  <div class=\"modal fade\" id=\"myModalFoto\" data-backdrop=\"static\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <!-- Modal Header -->\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <h4 class=\"modal-title\">Sistema</h4>\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("        </div>\n");
      out.write("        <form action=\"updateFoto\" method=\"post\" name=\"myForm\" enctype=\"multipart/form-data\">\t\n");
      out.write("\t        <!-- Modal body -->\n");
      out.write("\t        <div class=\"modal-body\">\n");
      out.write("\t        \t<input type=\"text\" id=\"idNumeroFoto\" name=\"medicamento.idMedicamento\">\n");
      out.write("\t\t\t  \t<img id=\"idFoto\">\n");
      out.write("\t\t\t  \t<div class=\"form-group\">\n");
      out.write("\t\t              <label for=\"staticEmail\">Foto</label>\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"medicamento.archivo\"/>\n");
      out.write("\t\t        </div>\n");
      out.write("\t\t\t  \t\n");
      out.write("\t        </div>\n");
      out.write("\t        \n");
      out.write("\t        <!-- Modal footer -->\n");
      out.write("\t        <div class=\"modal-footer\">\n");
      out.write("\t          <button type=\"submit\" class=\"btn btn-primary\">Actualizar</button>\n");
      out.write("\t\t      <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Cerrar</button>\n");
      out.write("\t\n");
      out.write("\t        </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<h3 align=\"center\">Lista de Medicamentos</h3>\n");
      out.write("\t\t<button type=\"button\" data-toggle='modal'  data-target=\"#idModalRegistra\" id=\"idNuevo\"\n");
      out.write("\t\t\t\tclass='btn btn-primary' >Nuevo Medicamento</button><br>&nbsp;<br>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t<div id=\"divEmpleado\">\n");
      out.write("\t\t \t\t\t\t\t\t\t\t<table id=\"idTable\" class=\"table table-striped table-bordered\" style=\"width:100%\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Codigo</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Nombre</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Descripción</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Stock</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Precio</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Fecha</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\t\n");
      out.write("\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("<!-- INICIO DIV NUEVO -->\n");
      out.write("<div class=\"modal fade bd-example-modal-lg\" id=\"idModalRegistra\" data-backdrop=\"static\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("\t\t\t\t<!-- Modal content-->\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"padding: 5px 20px\">\n");
      out.write("\t\t\t\t\tRegistro de Medicamento<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          \t\t\t\t\n");
      out.write("       \t\t\t\t   </button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 20px 20px;\">\n");
      out.write("\t\t\t\t\t<form id=\"idRegistra\" accept-charset=\"UTF-8\" action=\"saveMedicamento\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-horizontal\" method=\"post\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"validator\" role=\"form\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tenctype=\"multipart/form-data\">\t\t\t\t\t\t\n");
      out.write("\t\t                   \t\t\t\t<input type=\"hidden\" id=\"idCodigo\" name=\"medicamento.idMedicamento\" value=\"0\">\n");
      out.write("\t\t                                \t<div class=\"form-group\">\n");
      out.write("\t\t\t                                   \t<label for=\"staticEmail\">Nombre</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"idNombre\" name=\"medicamento.nombre\" placeholder=\"Ingrese el Nombre\"/>\n");
      out.write("\t\t\t                                </div>    \n");
      out.write("\t\t                                    <div class=\"form-group\">\n");
      out.write("\t\t                                       <label for=\"staticEmail\">Descripción</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   <textarea class=\"form-control\" id=\"idDescripcion\" name=\"medicamento.descripcion\" rows=\"3\" cols=\"10\" placeholder=\"Ingrese Descripción\"></textarea>\n");
      out.write("\t\t                                    </div>\n");
      out.write("\t\t                                    <div class=\"form-row\">\n");
      out.write("\t\t\t                                    <div class=\"form-group col-md-6\">\n");
      out.write("\t\t\t                                        <label for=\"staticEmail\">Stock</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"idStock\" name=\"medicamento.stock\" placeholder=\"Ingrese Stock\"/>\n");
      out.write("\t\t\t                                    </div>\n");
      out.write("\t\t\t                                    <div class=\"form-group col-md-6\">\n");
      out.write("\t\t\t                                        <label for=\"staticEmail\">Precio</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"idPrecio\" name=\"medicamento.precio\" placeholder=\"Ingrese Precio\"/>\n");
      out.write("\t\t\t                                    </div>\n");
      out.write("\t\t\t                                </div>    \n");
      out.write("\t\t                                    <div class=\"form-group\">\n");
      out.write("\t\t                                        <label for=\"staticEmail\">Fecha Fabricación</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"idFecha\" name=\"medicamento.fechaFabricacion\" placeholder=\"Ingrese Fecha Fabricación\"/>\n");
      out.write("\t\t                                    </div>\n");
      out.write("\t\t                                    <div class=\"form-group\">\n");
      out.write("\t\t                                        <label for=\"staticEmail\">Laboratorio</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"idLaboratorio\" name=\"medicamento.idLaboratorio\" class='form-control'>\n");
      out.write("\t\t\t\t\t\t\t                                 <option value=\" \" >[SELECCIONE]</option>\n");
      out.write("\t\t\t\t\t\t\t                         </select>\n");
      out.write("\t\t                                    </div>\n");
      out.write("\t\t                                    <div class=\"form-group\">\n");
      out.write("\t\t                                        <label for=\"staticEmail\">Tipo</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"idTipo\" name=\"medicamento.codigoTipo\" class='form-control'>\n");
      out.write("\t\t\t\t\t\t\t                                 <option value=\" \" >[SELECCIONE]</option>\n");
      out.write("\t\t\t\t\t\t\t                         </select>\n");
      out.write("\t\t                                    </div>\n");
      out.write("\t\t                                    <div class=\"form-group\">\n");
      out.write("\t\t                                        <label for=\"staticEmail\">Foto</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"medicamento.archivo\"/>\n");
      out.write("\t\t                                    </div>\n");
      out.write("                        \t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\" id=\"btnCerrar\">Cerrar</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t        <button type=\"submit\" class=\"btn btn-primary\">Guardar</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\n");
      out.write("\n");
      out.write("\t\t            </form>      \n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("</div>\n");
      out.write("  \n");
      out.write("<!-- FIN DIV NUEVO -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrapValidator.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("$(document).ready(function() {\n");
      out.write("\tllenarLaboratorios();\n");
      out.write("\tllenarMedicamentos();\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("//variable global\n");
      out.write("var codTipo=0;\n");
      out.write("\n");
      out.write("function llenarLaboratorios(){\n");
      out.write("\t$.getJSON(\"listaLaboratorio\",{},\n");
      out.write("\t\t\tfunction (data){\n");
      out.write("\t\t\t\t$.each(data.listaLaboratorios,function(index,item){\n");
      out.write("\t\t\t\t\t$(\"#idLaboratorio\").append(\"<option value='\"+item.idLaboratorio+\"'>\"+item.nombre+\"</option>\");\n");
      out.write("\t\t\t\t})\t\n");
      out.write("\t})\n");
      out.write("}\n");
      out.write("function llenarMedicamentos(){\n");
      out.write("\t$.getJSON(\"listAllMedicamentos\",{},\n");
      out.write("\t\t\tfunction (data){\n");
      out.write("\t\t\t\t$.each(data.listaMedicamentos,function(index,item){\n");
      out.write("\t\t\t\t\tvar buscar=\"<button type='button' class='btn btn-secondary' data-toggle='modal'  id='idEditar' data-target='#idModalRegistra'>Editar</button>\";\n");
      out.write("\t\t\t\t\tvar eliminar=\"<button type='button' class='btn btn-danger' data-toggle='modal' \"+\n");
      out.write("\t\t\t\t\t\t\t\t \"data-target='#myModal' id='idEliminar'>Eliminar</button>\";\n");
      out.write("\t\t\t\t\tvar foto=\"<button type='button' class='btn btn-danger' data-toggle='modal' \"+\n");
      out.write("\t\t\t\t\t\t\t\t \"data-target='#myModalFoto' id='btnFoto'>Foto</button>\";\t\t\t \n");
      out.write("\t\t\t\t\t$(\"#idTable\").append(\"<tr><td>\"+item.idMedicamento+\"</td><td>\"+item.nombre+\"</td><td>\"+item.descripcion+ \n");
      out.write("\t\t\t\t\t\t\t\t\t\t \"</td><td>\"+item.stock+\"</td><td>\"+item.precio+\"</td><td>\"+item.fechaFabricacion+\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \"</td><td>\"+buscar+\"</td><td>\"+eliminar+\"</td><td>\"+foto+\"</td></tr>\");\n");
      out.write("\t\t\t\t})\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(\"#idTable\").DataTable();\n");
      out.write("\t\t\t\t\n");
      out.write("\t})\n");
      out.write("}\n");
      out.write("\n");
      out.write("$(\"#success-alert\").fadeTo(3000,1, function(){\t\n");
      out.write("    $(\"#success-alert\").slideUp(500);\n");
      out.write("\n");
      out.write("});\n");
      out.write("\n");
      out.write("$(document).on('click', '#idEliminar', function(){\n");
      out.write("    var id = $(this).parents(\"tr\").find(\"td\")[0].innerHTML;\n");
      out.write("    $(\"#idNumero\").val(id);\n");
      out.write("})\n");
      out.write("\n");
      out.write("$(document).on('click', '#idEditar', function(){\n");
      out.write("    var id = $(this).parents(\"tr\").find(\"td\")[0].innerHTML;\n");
      out.write("    $.getJSON(\"findMedicamento\",{codigo:id},function (response){\n");
      out.write("\t\t$(\"#idCodigo\").val(id); \n");
      out.write("\t\t$(\"#idNombre\").val(response.medicamento.nombre);\n");
      out.write("\t\t$(\"#idDescripcion\").val(response.medicamento.descripcion);\n");
      out.write("\t\t$(\"#idStock\").val(response.medicamento.stock);\n");
      out.write("\t\t$(\"#idPrecio\").val(response.medicamento.precio);\n");
      out.write("\t\t$(\"#idFecha\").val(response.medicamento.fechaFabricacion);\n");
      out.write("\t\t$(\"#idLaboratorio\").val(response.medicamento.idLaboratorio);\n");
      out.write("\t\t//alacenar el valor de tipo de medicamento en la variable global codTipo\n");
      out.write("\t\tcodTipo=response.medicamento.codigoTipo;\n");
      out.write("\t\t//invocar al evento change del select idLaboratorio\n");
      out.write("\t\t$(\"#idLaboratorio\").trigger(\"change\");\n");
      out.write("    })  \n");
      out.write("})\n");
      out.write("$(document).on('click', '#btnCerrar', function(){\n");
      out.write("\t$('#idRegistra').data('bootstrapValidator').resetForm(true);\n");
      out.write("    $('#idRegistra').trigger(\"reset\");\n");
      out.write("\t$(\"#idCodigo\").val(0); \n");
      out.write("})\n");
      out.write("$(document).on('click', '#btnFoto', function(){\n");
      out.write("\t var id = $(this).parents(\"tr\").find(\"td\")[0].innerHTML;\n");
      out.write("\t $(\"#idNumeroFoto\").val(id);\n");
      out.write("\t \n");
      out.write("\t $.getJSON(\"findFotoMedicamento\",{codigo:id},function (response){\n");
      out.write("\t\t if(response.baseFoto!=null)\n");
      out.write("\t\t \t$(\"#idFoto\").attr(\"src\",\"data:image/jpg;base64,\"+response.baseFoto);\n");
      out.write("\t\t else\n");
      out.write("\t\t\t $(\"#idFoto\").attr(\"src\",\"img/image-not-found.png\");\n");
      out.write("\t })\n");
      out.write("})\n");
      out.write("\n");
      out.write("//asignar evento change al select \"idLaboratorio\"\n");
      out.write("$(\"#idLaboratorio\").change(function(){\n");
      out.write("\t//obtner el id del laboratorio seleccionado\n");
      out.write("\tvar idLab;\n");
      out.write("\tidLab=$(this).val();\n");
      out.write("\t$.getJSON(\"listaTipo\",{idLaboratorio:idLab},function (response){\n");
      out.write("\t\t//limpiar select idTipo\n");
      out.write("\t\t$(\"#idTipo\").empty().append(\"<option value=''>[Seleccione Tipo]</option>\")\n");
      out.write("\t\t$.each(response.listaTipos,function(index,item){\n");
      out.write("\t\t\t//validar \n");
      out.write("\t\t\tif(codTipo==item.codigoTipo)\n");
      out.write("\t\t\t\t$(\"#idTipo\").append(\"<option value='\"+item.codigoTipo+\"' selected>\"+item.nombre+\"</option>\");\n");
      out.write("\t\t\telse\n");
      out.write("\t\t\t\t$(\"#idTipo\").append(\"<option value='\"+item.codigoTipo+\"'>\"+item.nombre+\"</option>\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t})\n");
      out.write("\t})\n");
      out.write("})\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">    \n");
      out.write("    $(document).ready(function(){     \n");
      out.write("        $('#idRegistra').bootstrapValidator({      \n");
      out.write("        \t fields:{\n");
      out.write("        \t\t \n");
      out.write("        \t\t Nombre: {\n");
      out.write("     \t    \t\tselector:'#idNombre',   \n");
      out.write("                    validators: {    \n");
      out.write("                        notEmpty: {    \n");
      out.write("                            message: 'Ingrese nombre'    \n");
      out.write("                        },      \n");
      out.write("                        regexp: {    \n");
      out.write("                            regexp: /^[a-zA-Z\\s]+$/,    \n");
      out.write("                            message: 'The username can only consist of alphabetical, number, dot and underscore'    \n");
      out.write("                        },    \n");
      out.write("                    }    \n");
      out.write("                },   \n");
      out.write("                Descripcion: {\n");
      out.write("     \t    \t\tselector:'#idDescripcion',       \n");
      out.write("                    validators: {    \n");
      out.write("                        notEmpty: {    \n");
      out.write("                            message: 'Ingrese Descrpción'    \n");
      out.write("                        }   \n");
      out.write("                    }    \n");
      out.write("                },    \n");
      out.write("                Stock: {\n");
      out.write("     \t    \t\tselector:'#idStock',      \n");
      out.write("                    validators: {    \n");
      out.write("                        notEmpty: {    \n");
      out.write("                            message: 'Ingrese Stock'    \n");
      out.write("                        },       \n");
      out.write("                    }    \n");
      out.write("                },    \n");
      out.write("                Precio: {\n");
      out.write("     \t    \t\tselector:'#idPrecio',     \n");
      out.write("                    validators: {    \n");
      out.write("                        notEmpty: {    \n");
      out.write("                            message: 'Ingrese Precio'    \n");
      out.write("                        },       \n");
      out.write("                    }    \n");
      out.write("                }, \n");
      out.write("                Fecha: {\n");
      out.write("     \t    \t\tselector:'#idFecha',   \n");
      out.write("                    validators: {    \n");
      out.write("                        notEmpty: {    \n");
      out.write("                            message: 'Ingrese Fecha'    \n");
      out.write("                        },\t\t\t\t\t\n");
      out.write("                    }    \n");
      out.write("                },   \t\t\t\t\n");
      out.write("                Laboratorio: {\n");
      out.write("     \t    \t\tselector:'#idLaboratorio',   \n");
      out.write("                    validators: {    \n");
      out.write("                        notEmpty: {    \n");
      out.write("                            message: 'Seleccione Laboratorio'    \n");
      out.write("                        },\t\t\t\t\t\n");
      out.write("                    }    \n");
      out.write("                } \n");
      out.write("        \t }\n");
      out.write("        });   \n");
      out.write("\t\t\t\n");
      out.write("    });    \n");
      out.write("</script>   \n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /informemultiple.jsp(51,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\" id=\"success-alert\">\n");
          out.write("  <strong>Sistema:</strong> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("  <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\n");
          out.write("    <span aria-hidden=\"true\">&times;</span>\n");
          out.write("  </button>\n");
          out.write("</div>\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent(null);
      // /informemultiple.jsp(59,0) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("MENSAJE");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
